### ISSUE TITLE
Добавить README

### ISSUE THREAD

**Issue by ghost** [sn0w13/-#1]
если в корне вашего репозитория будет лежать файл со специальным именем - гитхаб обработает его особым образом.
В этом файле обычно пишут описание проекта, про что он, как работает, кто автор и т.п. 
Создайте в вашем репозитории файл с именем “README” (без расширения), в нем напишите описание вашего репозитория. Например “Это учебный репозиторий, в нем я изучаю как работают разные штуки в github. Я уже научился добавлять и изменять файлы, работать с ишузами”.
После создания файла перейдите в репозиторий и посмотрите что изменилось (должно появиться что-то снизу от файлов репозитория). 

Напишите об этом в комментарии к ишузу, добавьте в комментарий ишуза скриншот как выглядит главная страница репозитория после добавления файла и закройте его как выполненный

**Comment by sn0w13** [comment]
![Readme](https://github.com/sn0w13/Test/assets/164729502/89fb9d25-2aa4-40da-a685-81d46ce77990)

**Comment by sn0w13** [comment]
Готово.
